/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_indeed_flamdex_fieldcache_NativeFlamdexFieldCacher */

#ifndef _Included_com_indeed_flamdex_fieldcache_NativeFlamdexFieldCacher
#define _Included_com_indeed_flamdex_fieldcache_NativeFlamdexFieldCacher
#ifdef __cplusplus
extern "C" {
#endif
#undef com_indeed_flamdex_fieldcache_NativeFlamdexFieldCacher_BUFFER_SIZE
#define com_indeed_flamdex_fieldcache_NativeFlamdexFieldCacher_BUFFER_SIZE 8192L
/*
 * Class:     com_indeed_flamdex_fieldcache_NativeFlamdexFieldCacher
 * Method:    nativeCacheBitsetMetricValuesMmap
 * Signature: (JIJJ)V
 */
JNIEXPORT void JNICALL Java_com_indeed_flamdex_fieldcache_NativeFlamdexFieldCacher_nativeCacheBitsetMetricValuesMmap
  (JNIEnv *, jclass, jlong, jint, jlong, jlong);

/*
 * Class:     com_indeed_flamdex_fieldcache_NativeFlamdexFieldCacher
 * Method:    nativeCacheBitsetMetricValuesInArray
 * Signature: ([JIJJ)V
 */
JNIEXPORT void JNICALL Java_com_indeed_flamdex_fieldcache_NativeFlamdexFieldCacher_nativeCacheBitsetMetricValuesInArray
  (JNIEnv *, jclass, jlongArray, jint, jlong, jlong);

/*
 * Class:     com_indeed_flamdex_fieldcache_NativeFlamdexFieldCacher
 * Method:    nativeCacheCharMetricValuesMMap
 * Signature: (J[C[IJ[JI)V
 */
JNIEXPORT void JNICALL Java_com_indeed_flamdex_fieldcache_NativeFlamdexFieldCacher_nativeCacheCharMetricValuesMMap
  (JNIEnv *, jclass, jlong, jcharArray, jintArray, jlong, jlongArray, jint);

/*
 * Class:     com_indeed_flamdex_fieldcache_NativeFlamdexFieldCacher
 * Method:    nativeCacheCharMetricValuesInArray
 * Signature: ([C[C[IJ[JI)V
 */
JNIEXPORT void JNICALL Java_com_indeed_flamdex_fieldcache_NativeFlamdexFieldCacher_nativeCacheCharMetricValuesInArray
  (JNIEnv *, jclass, jcharArray, jcharArray, jintArray, jlong, jlongArray, jint);

/*
 * Class:     com_indeed_flamdex_fieldcache_NativeFlamdexFieldCacher
 * Method:    nativeCacheByteMetricValuesMMap
 * Signature: (J[B[IJ[JI)V
 */
JNIEXPORT void JNICALL Java_com_indeed_flamdex_fieldcache_NativeFlamdexFieldCacher_nativeCacheByteMetricValuesMMap
  (JNIEnv *, jclass, jlong, jbyteArray, jintArray, jlong, jlongArray, jint);

/*
 * Class:     com_indeed_flamdex_fieldcache_NativeFlamdexFieldCacher
 * Method:    nativeCacheByteMetricValuesInArray
 * Signature: ([B[B[IJ[JI)V
 */
JNIEXPORT void JNICALL Java_com_indeed_flamdex_fieldcache_NativeFlamdexFieldCacher_nativeCacheByteMetricValuesInArray
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jintArray, jlong, jlongArray, jint);

/*
 * Class:     com_indeed_flamdex_fieldcache_NativeFlamdexFieldCacher
 * Method:    nativeCacheShortMetricValuesMMap
 * Signature: (J[S[IJ[JI)V
 */
JNIEXPORT void JNICALL Java_com_indeed_flamdex_fieldcache_NativeFlamdexFieldCacher_nativeCacheShortMetricValuesMMap
  (JNIEnv *, jclass, jlong, jshortArray, jintArray, jlong, jlongArray, jint);

/*
 * Class:     com_indeed_flamdex_fieldcache_NativeFlamdexFieldCacher
 * Method:    nativeCacheShortMetricValuesInArray
 * Signature: ([S[S[IJ[JI)V
 */
JNIEXPORT void JNICALL Java_com_indeed_flamdex_fieldcache_NativeFlamdexFieldCacher_nativeCacheShortMetricValuesInArray
  (JNIEnv *, jclass, jshortArray, jshortArray, jintArray, jlong, jlongArray, jint);

/*
 * Class:     com_indeed_flamdex_fieldcache_NativeFlamdexFieldCacher
 * Method:    nativeCacheIntMetricValuesMMap
 * Signature: (J[I[IJ[JI)V
 */
JNIEXPORT void JNICALL Java_com_indeed_flamdex_fieldcache_NativeFlamdexFieldCacher_nativeCacheIntMetricValuesMMap
  (JNIEnv *, jclass, jlong, jintArray, jintArray, jlong, jlongArray, jint);

/*
 * Class:     com_indeed_flamdex_fieldcache_NativeFlamdexFieldCacher
 * Method:    nativeCacheIntMetricValuesInArray
 * Signature: ([I[I[IJ[JI)V
 */
JNIEXPORT void JNICALL Java_com_indeed_flamdex_fieldcache_NativeFlamdexFieldCacher_nativeCacheIntMetricValuesInArray
  (JNIEnv *, jclass, jintArray, jintArray, jintArray, jlong, jlongArray, jint);

/*
 * Class:     com_indeed_flamdex_fieldcache_NativeFlamdexFieldCacher
 * Method:    nativeCacheLongMetricValuesMMap
 * Signature: (J[J[IJ[JI)V
 */
JNIEXPORT void JNICALL Java_com_indeed_flamdex_fieldcache_NativeFlamdexFieldCacher_nativeCacheLongMetricValuesMMap
  (JNIEnv *, jclass, jlong, jlongArray, jintArray, jlong, jlongArray, jint);

/*
 * Class:     com_indeed_flamdex_fieldcache_NativeFlamdexFieldCacher
 * Method:    nativeCacheLongMetricValuesInArray
 * Signature: ([J[J[IJ[JI)V
 */
JNIEXPORT void JNICALL Java_com_indeed_flamdex_fieldcache_NativeFlamdexFieldCacher_nativeCacheLongMetricValuesInArray
  (JNIEnv *, jclass, jlongArray, jlongArray, jintArray, jlong, jlongArray, jint);

#ifdef __cplusplus
}
#endif
#endif
