/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_indeed_imhotep_local_MTImhotepLocalMultiSession */

#ifndef _Included_com_indeed_imhotep_local_MTImhotepLocalMultiSession
#define _Included_com_indeed_imhotep_local_MTImhotepLocalMultiSession
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_indeed_imhotep_local_MTImhotepLocalMultiSession
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_indeed_imhotep_local_MTImhotepLocalMultiSession_nativeInit
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
