/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_indeed_imhotep_local_NativeShard */

#ifndef _Included_com_indeed_imhotep_local_NativeShard
#define _Included_com_indeed_imhotep_local_NativeShard
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_indeed_imhotep_local_NativeShard
 * Method:    nativeGetShard
 * Signature: (Ljava/lang/String;[Ljava/lang/String;[Ljava/lang/String;J[Ljava/lang/String;[J)J
 */
JNIEXPORT jlong JNICALL Java_com_indeed_imhotep_local_NativeShard_nativeGetShard
  (JNIEnv *, jclass, jstring, jobjectArray, jobjectArray, jlong, jobjectArray, jlongArray);

/*
 * Class:     com_indeed_imhotep_local_NativeShard
 * Method:    nativeReleaseShard
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_indeed_imhotep_local_NativeShard_nativeReleaseShard
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_indeed_imhotep_local_NativeShard
 * Method:    nativeToString
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_indeed_imhotep_local_NativeShard_nativeToString
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
