/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_indeed_imhotep_local_NativeMetricRegroupInternals */

#ifndef _Included_com_indeed_imhotep_local_NativeMetricRegroupInternals
#define _Included_com_indeed_imhotep_local_NativeMetricRegroupInternals
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_indeed_imhotep_local_NativeMetricRegroupInternals
 * Method:    getMagicNumber
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_indeed_imhotep_local_NativeMetricRegroupInternals_getMagicNumber
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_indeed_imhotep_local_NativeMetricRegroupInternals
 * Method:    calculateGroups
 * Signature: (IIJIIJJ)V
 */
JNIEXPORT void JNICALL Java_com_indeed_imhotep_local_NativeMetricRegroupInternals_calculateGroups
  (JNIEnv *, jclass, jint, jint, jlong, jint, jint, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
