/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_indeed_imhotep_local_MultiCache_MultiCacheIntValueLookup */

#ifndef _Included_com_indeed_imhotep_local_MultiCache_MultiCacheIntValueLookup
#define _Included_com_indeed_imhotep_local_MultiCache_MultiCacheIntValueLookup
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_indeed_imhotep_local_MultiCache_MultiCacheIntValueLookup
 * Method:    nativeMetricLookup
 * Signature: (JI[I[JI)V
 */
JNIEXPORT void JNICALL Java_com_indeed_imhotep_local_MultiCache_00024MultiCacheIntValueLookup_nativeMetricLookup
  (JNIEnv *, jobject, jlong, jint, jintArray, jlongArray, jint);

#ifdef __cplusplus
}
#endif
#endif
