/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_indeed_imhotep_multicache_ftgs_NativeFTGSWorker */

#ifndef _Included_com_indeed_imhotep_multicache_ftgs_NativeFTGSWorker
#define _Included_com_indeed_imhotep_multicache_ftgs_NativeFTGSWorker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_indeed_imhotep_multicache_ftgs_NativeFTGSWorker
 * Method:    native_start_field
 * Signature: (JJ[BIZ)I
 */
JNIEXPORT jint JNICALL Java_com_indeed_imhotep_multicache_ftgs_NativeFTGSWorker_native_1start_1field
  (JNIEnv *, jclass, jlong, jlong, jbyteArray, jint, jboolean);

/*
 * Class:     com_indeed_imhotep_multicache_ftgs_NativeFTGSWorker
 * Method:    native_end_field
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_indeed_imhotep_multicache_ftgs_NativeFTGSWorker_native_1end_1field
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_indeed_imhotep_multicache_ftgs_NativeFTGSWorker
 * Method:    native_run_string_tgs_pass
 * Signature: (JJ[BI[J[III)I
 */
JNIEXPORT jint JNICALL Java_com_indeed_imhotep_multicache_ftgs_NativeFTGSWorker_native_1run_1string_1tgs_1pass
  (JNIEnv *, jclass, jlong, jlong, jbyteArray, jint, jlongArray, jintArray, jint, jint);

/*
 * Class:     com_indeed_imhotep_multicache_ftgs_NativeFTGSWorker
 * Method:    native_run_int_tgs_pass
 * Signature: (JJJ[J[III)I
 */
JNIEXPORT jint JNICALL Java_com_indeed_imhotep_multicache_ftgs_NativeFTGSWorker_native_1run_1int_1tgs_1pass
  (JNIEnv *, jclass, jlong, jlong, jlong, jlongArray, jintArray, jint, jint);

/*
 * Class:     com_indeed_imhotep_multicache_ftgs_NativeFTGSWorker
 * Method:    native_session_create
 * Signature: (J[JIII)J
 */
JNIEXPORT jlong JNICALL Java_com_indeed_imhotep_multicache_ftgs_NativeFTGSWorker_native_1session_1create
  (JNIEnv *, jclass, jlong, jlongArray, jint, jint, jint);

/*
 * Class:     com_indeed_imhotep_multicache_ftgs_NativeFTGSWorker
 * Method:    native_session_destroy
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_indeed_imhotep_multicache_ftgs_NativeFTGSWorker_native_1session_1destroy
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_indeed_imhotep_multicache_ftgs_NativeFTGSWorker
 * Method:    native_init
 * Signature: (III[II)J
 */
JNIEXPORT jlong JNICALL Java_com_indeed_imhotep_multicache_ftgs_NativeFTGSWorker_native_1init
  (JNIEnv *, jclass, jint, jint, jint, jintArray, jint);

/*
 * Class:     com_indeed_imhotep_multicache_ftgs_NativeFTGSWorker
 * Method:    native_worker_destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_indeed_imhotep_multicache_ftgs_NativeFTGSWorker_native_1worker_1destroy
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
