/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_indeed_imhotep_local_PackedTableView */

#ifndef _Included_com_indeed_imhotep_local_PackedTableView
#define _Included_com_indeed_imhotep_local_PackedTableView
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_indeed_imhotep_local_PackedTableView
 * Method:    nativeBind
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_indeed_imhotep_local_PackedTableView_nativeBind
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
