/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_indeed_imhotep_service_PinnedThreadFactory */

#ifndef _Included_com_indeed_imhotep_service_PinnedThreadFactory
#define _Included_com_indeed_imhotep_service_PinnedThreadFactory
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_indeed_imhotep_service_PinnedThreadFactory_PinnedThread */

#ifndef _Included_com_indeed_imhotep_service_PinnedThreadFactory_PinnedThread
#define _Included_com_indeed_imhotep_service_PinnedThreadFactory_PinnedThread
#ifdef __cplusplus
extern "C" {
#endif
#undef com_indeed_imhotep_service_PinnedThreadFactory_PinnedThread_MIN_PRIORITY
#define com_indeed_imhotep_service_PinnedThreadFactory_PinnedThread_MIN_PRIORITY 1L
#undef com_indeed_imhotep_service_PinnedThreadFactory_PinnedThread_NORM_PRIORITY
#define com_indeed_imhotep_service_PinnedThreadFactory_PinnedThread_NORM_PRIORITY 5L
#undef com_indeed_imhotep_service_PinnedThreadFactory_PinnedThread_MAX_PRIORITY
#define com_indeed_imhotep_service_PinnedThreadFactory_PinnedThread_MAX_PRIORITY 10L
/*
 * Class:     com_indeed_imhotep_service_PinnedThreadFactory_PinnedThread
 * Method:    pin
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_indeed_imhotep_service_PinnedThreadFactory_00024PinnedThread_pin
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
