/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_indeed_imhotep_local_ImhotepNativeLocalSession */

#ifndef _Included_com_indeed_imhotep_local_ImhotepNativeLocalSession
#define _Included_com_indeed_imhotep_local_ImhotepNativeLocalSession
#ifdef __cplusplus
extern "C" {
#endif
#undef com_indeed_imhotep_local_ImhotepNativeLocalSession_MAX_NUMBER_STATS
#define com_indeed_imhotep_local_ImhotepNativeLocalSession_MAX_NUMBER_STATS 64L
#undef com_indeed_imhotep_local_ImhotepNativeLocalSession_BUFFER_SIZE
#define com_indeed_imhotep_local_ImhotepNativeLocalSession_BUFFER_SIZE 2048L
/*
 * Class:     com_indeed_imhotep_local_ImhotepNativeLocalSession
 * Method:    nativeGetGroupStats
 * Signature: (I[J)V
 */
JNIEXPORT void JNICALL Java_com_indeed_imhotep_local_ImhotepNativeLocalSession_nativeGetGroupStats
  (JNIEnv *, jobject, jint, jlongArray);

#ifdef __cplusplus
}
#endif
#endif
