/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_indeed_imhotep_local_MultiRegroupInternals */

#ifndef _Included_com_indeed_imhotep_local_MultiRegroupInternals
#define _Included_com_indeed_imhotep_local_MultiRegroupInternals
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_indeed_imhotep_local_MultiRegroupInternals
 * Method:    nativeRemapDocsInTargetGroups
 * Signature: (J[BJI[II)V
 */
JNIEXPORT void JNICALL Java_com_indeed_imhotep_local_MultiRegroupInternals_nativeRemapDocsInTargetGroups__J_3BJI_3II
  (JNIEnv *, jclass, jlong, jbyteArray, jlong, jint, jintArray, jint);

/*
 * Class:     com_indeed_imhotep_local_MultiRegroupInternals
 * Method:    nativeRemapDocsInTargetGroups
 * Signature: (J[CJI[II)V
 */
JNIEXPORT void JNICALL Java_com_indeed_imhotep_local_MultiRegroupInternals_nativeRemapDocsInTargetGroups__J_3CJI_3II
  (JNIEnv *, jclass, jlong, jcharArray, jlong, jint, jintArray, jint);

/*
 * Class:     com_indeed_imhotep_local_MultiRegroupInternals
 * Method:    nativeRemapDocsInTargetGroups
 * Signature: (J[IJI[II)V
 */
JNIEXPORT void JNICALL Java_com_indeed_imhotep_local_MultiRegroupInternals_nativeRemapDocsInTargetGroups__J_3IJI_3II
  (JNIEnv *, jclass, jlong, jintArray, jlong, jint, jintArray, jint);

#ifdef __cplusplus
}
#endif
#endif
