/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_indeed_imhotep_local_MultiCache_MultiCacheGroupLookup */

#ifndef _Included_com_indeed_imhotep_local_MultiCache_MultiCacheGroupLookup
#define _Included_com_indeed_imhotep_local_MultiCache_MultiCacheGroupLookup
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_indeed_imhotep_local_MultiCache_MultiCacheGroupLookup
 * Method:    nativeFillGroupsBuffer
 * Signature: (J[I[II)V
 */
JNIEXPORT void JNICALL Java_com_indeed_imhotep_local_MultiCache_00024MultiCacheGroupLookup_nativeFillGroupsBuffer
  (JNIEnv *, jobject, jlong, jintArray, jintArray, jint);

/*
 * Class:     com_indeed_imhotep_local_MultiCache_MultiCacheGroupLookup
 * Method:    nativeUpdateGroups
 * Signature: (J[I[II)V
 */
JNIEXPORT void JNICALL Java_com_indeed_imhotep_local_MultiCache_00024MultiCacheGroupLookup_nativeUpdateGroups
  (JNIEnv *, jobject, jlong, jintArray, jintArray, jint);

/*
 * Class:     com_indeed_imhotep_local_MultiCache_MultiCacheGroupLookup
 * Method:    nativeUpdateGroupsSequential
 * Signature: (JII[I)V
 */
JNIEXPORT void JNICALL Java_com_indeed_imhotep_local_MultiCache_00024MultiCacheGroupLookup_nativeUpdateGroupsSequential
  (JNIEnv *, jobject, jlong, jint, jint, jintArray);

/*
 * Class:     com_indeed_imhotep_local_MultiCache_MultiCacheGroupLookup
 * Method:    nativeGetGroup
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_indeed_imhotep_local_MultiCache_00024MultiCacheGroupLookup_nativeGetGroup
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_indeed_imhotep_local_MultiCache_MultiCacheGroupLookup
 * Method:    nativeSetGroupForDoc
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_com_indeed_imhotep_local_MultiCache_00024MultiCacheGroupLookup_nativeSetGroupForDoc
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     com_indeed_imhotep_local_MultiCache_MultiCacheGroupLookup
 * Method:    nativeSetAllGroups
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_indeed_imhotep_local_MultiCache_00024MultiCacheGroupLookup_nativeSetAllGroups
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_indeed_imhotep_local_MultiCache_MultiCacheGroupLookup
 * Method:    nativeBitSetRegroup
 * Signature: (J[JIII)V
 */
JNIEXPORT void JNICALL Java_com_indeed_imhotep_local_MultiCache_00024MultiCacheGroupLookup_nativeBitSetRegroup
  (JNIEnv *, jobject, jlong, jlongArray, jint, jint, jint);

/*
 * Class:     com_indeed_imhotep_local_MultiCache_MultiCacheGroupLookup
 * Method:    nativeRecalculateNumGroups
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_indeed_imhotep_local_MultiCache_00024MultiCacheGroupLookup_nativeRecalculateNumGroups
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
