/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_indeed_imhotep_local_MultiCache */

#ifndef _Included_com_indeed_imhotep_local_MultiCache
#define _Included_com_indeed_imhotep_local_MultiCache
#ifdef __cplusplus
extern "C" {
#endif
#undef com_indeed_imhotep_local_MultiCache_MAX_GROUP_NUM
#define com_indeed_imhotep_local_MultiCache_MAX_GROUP_NUM 268435456L
#undef com_indeed_imhotep_local_MultiCache_BLOCK_COPY_SIZE
#define com_indeed_imhotep_local_MultiCache_BLOCK_COPY_SIZE 8192L
/*
 * Class:     com_indeed_imhotep_local_MultiCache
 * Method:    nativeDestroyMultiCache
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_indeed_imhotep_local_MultiCache_nativeDestroyMultiCache
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_indeed_imhotep_local_MultiCache
 * Method:    nativeBuildMultiCache
 * Signature: (I[J[J[I[I[I[BI)J
 */
JNIEXPORT jlong JNICALL Java_com_indeed_imhotep_local_MultiCache_nativeBuildMultiCache
  (JNIEnv *, jobject, jint, jlongArray, jlongArray, jintArray, jintArray, jintArray, jbyteArray, jint);

/*
 * Class:     com_indeed_imhotep_local_MultiCache
 * Method:    nativePackMetricDataInRange
 * Signature: (JIII[J)V
 */
JNIEXPORT void JNICALL Java_com_indeed_imhotep_local_MultiCache_nativePackMetricDataInRange
  (JNIEnv *, jclass, jlong, jint, jint, jint, jlongArray);

/*
 * Class:     com_indeed_imhotep_local_MultiCache
 * Method:    nativeSetGroupsInRange
 * Signature: (JII[I)V
 */
JNIEXPORT void JNICALL Java_com_indeed_imhotep_local_MultiCache_nativeSetGroupsInRange
  (JNIEnv *, jobject, jlong, jint, jint, jintArray);

#ifdef __cplusplus
}
#endif
#endif
