/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_indeed_imhotep_local_NativeFTGSWorker */

#ifndef _Included_com_indeed_imhotep_local_NativeFTGSWorker
#define _Included_com_indeed_imhotep_local_NativeFTGSWorker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_indeed_imhotep_local_NativeFTGSWorker
 * Method:    native_run_int_tgs_pass
 * Signature: (JJI[J[I[III)I
 */
JNIEXPORT jint JNICALL Java_com_indeed_imhotep_local_NativeFTGSWorker_native_1run_1int_1tgs_1pass
  (JNIEnv *, jclass, jlong, jlong, jint, jlongArray, jintArray, jintArray, jint, jint);

/*
 * Class:     com_indeed_imhotep_local_NativeFTGSWorker
 * Method:    native_session_create
 * Signature: (JIII)J
 */
JNIEXPORT jlong JNICALL Java_com_indeed_imhotep_local_NativeFTGSWorker_native_1session_1create
  (JNIEnv *, jclass, jlong, jint, jint, jint);

/*
 * Class:     com_indeed_imhotep_local_NativeFTGSWorker
 * Method:    native_init
 * Signature: (III[II)J
 */
JNIEXPORT jlong JNICALL Java_com_indeed_imhotep_local_NativeFTGSWorker_native_1init
  (JNIEnv *, jclass, jint, jint, jint, jintArray, jint);

#ifdef __cplusplus
}
#endif
#endif
