/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_indeed_imhotep_local_NativeFTGSWorker_TermDescList */

#ifndef _Included_com_indeed_imhotep_local_NativeFTGSWorker_TermDescList
#define _Included_com_indeed_imhotep_local_NativeFTGSWorker_TermDescList
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
