/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_indeed_imhotep_local_MTImhotepLocalMultiSession */

#ifndef _Included_com_indeed_imhotep_local_MTImhotepLocalMultiSession
#define _Included_com_indeed_imhotep_local_MTImhotepLocalMultiSession
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_indeed_imhotep_local_MTImhotepLocalMultiSession
 * Method:    nativeFTGS
 * Signature: ([Ljava/lang/String;[J[Ljava/lang/String;[Ljava/lang/String;Ljava/lang/String;IIII[I)V
 */
JNIEXPORT void JNICALL Java_com_indeed_imhotep_local_MTImhotepLocalMultiSession_nativeFTGS
  (JNIEnv *, jobject, jobjectArray, jlongArray, jobjectArray, jobjectArray, jstring, jint, jint, jint, jint, jintArray);


#ifdef __cplusplus
}
#endif
#endif
